### ISSUE TITLE
Conflict in materials.xLamina.calcsLauncher module

### ISSUE THREAD

**Issue by anaiortega** [lcpt/XCmanual#1]
Resolve conflict:
'ascii' codec can't decode byte 0xc3 in position 849: ordinal not in range(128)
and insert module in materials.xLamina.rst

**Comment by lcpt** [comment]
If you don' upload your changes into the 'xc' repository I can't reproduce the problem.

**Comment by anaiortega** [comment]
Done!
By the way, I'm done with the documentation reordering. When you know 
the tricks, you go fast

**Comment by lcpt** [comment]
Problem solved (the problem was with accents in # style comments like in '# Sección'.)
The module is DEPRECATED so no need to include it in the documentation.
